from __future__ import annotations

import argparse
import base64
import re
import shutil
import subprocess
import sys
from importlib.util import module_from_spec, spec_from_file_location
from io import BytesIO
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile


ROOT = Path(__file__).resolve().parents[1]
GENERATED_DIR = ROOT / "packaging" / "_generated"
HOOKS_DIR = ROOT / "packaging" / "hooks"


def _run(cmd: list[str]) -> None:
    subprocess.check_call(cmd, cwd=ROOT)


def _safe_version() -> str:
    version_file = ROOT / "modbus_version.py"
    try:
        spec = spec_from_file_location("modbus_version", version_file)
        if spec and spec.loader:
            module = module_from_spec(spec)
            spec.loader.exec_module(module)
            value = getattr(module, "APP_VERSION", None)
            if value:
                return str(value)
    except Exception:
        pass

    try:
        value = subprocess.check_output(["git", "describe", "--tags", "--always"], cwd=ROOT, text=True).strip()
        return value.lstrip("v")
    except Exception:
        return "0.0.0"


def _version_tuple(version: str) -> tuple[int, int, int, int]:
    numbers = [int(part) for part in re.findall(r"\d+", version)]
    while len(numbers) < 3:
        numbers.append(0)
    return numbers[0], numbers[1], numbers[2], 0


def _write_windows_version_file(path: Path, version: str, exe_name: str) -> None:
    major, minor, patch, build = _version_tuple(version)

    content = f"""# UTF-8
#
# Auto-generated by scripts/build_portable.py
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, {build}),
    prodvers=({major}, {minor}, {patch}, {build}),
    mask=0x3f,
    flags=0x0,
    OS=0x4,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
    ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        '040904B0',
        [
        StringStruct('CompanyName', 'Blue Star Qatar'),
        StringStruct('FileDescription', 'Modbus Scanner'),
        StringStruct('FileVersion', '{version}'),
        StringStruct('InternalName', '{exe_name}'),
        StringStruct('OriginalFilename', '{exe_name}.exe'),
        StringStruct('ProductName', 'Modbus Scanner'),
        StringStruct('ProductVersion', '{version}')
        ])
      ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    path.write_text(content, encoding="utf-8")


def _write_icon(path: Path) -> bool:
    try:
        from PIL import Image
    except Exception:
        return False

    try:
        from modbus_ui import get_logo_base64
    except Exception:
        return False

    try:
        png_bytes = base64.b64decode(get_logo_base64())
        logo = Image.open(BytesIO(png_bytes)).convert("RGBA")
        canvas_size = 256
        canvas = Image.new("RGBA", (canvas_size, canvas_size), (232, 241, 255, 255))

        max_w = int(canvas_size * 0.78)
        max_h = int(canvas_size * 0.78)
        scale = min(max_w / logo.width, max_h / logo.height, 1.0)
        resized = logo.resize((int(logo.width * scale), int(logo.height * scale)), Image.LANCZOS)
        x = (canvas_size - resized.width) // 2
        y = (canvas_size - resized.height) // 2
        canvas.paste(resized, (x, y), resized)

        path.parent.mkdir(parents=True, exist_ok=True)
        canvas.save(
            path,
            format="ICO",
            sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)],
        )
        return True
    except Exception:
        return False


def _zip_portable(exe_path: Path, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with ZipFile(output_path, "w", compression=ZIP_DEFLATED) as archive:
        archive.write(exe_path, arcname=exe_path.name)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build a one-file portable executable with PyInstaller.")
    parser.add_argument("--name", default="ModbusScanner", help="Executable base name (default: ModbusScanner).")
    parser.add_argument("--no-clean", action="store_true", help="Do not delete build/dist before building.")
    parser.add_argument("--no-zip", action="store_true", help="Do not produce a portable .zip output.")
    args = parser.parse_args(argv)

    try:
        import PyInstaller  # noqa: F401
    except Exception:
        print("PyInstaller is not installed. Install dev deps: `pip install -r requirements-dev.txt`.", file=sys.stderr)
        return 2

    version = _safe_version()
    exe_name = args.name

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    icon_path = GENERATED_DIR / "app.ico"
    version_path = GENERATED_DIR / "version_info.txt"

    icon_ok = _write_icon(icon_path)
    if sys.platform.startswith("win"):
        _write_windows_version_file(version_path, version, exe_name)

    if not args.no_clean:
        shutil.rmtree(ROOT / "build", ignore_errors=True)
        shutil.rmtree(ROOT / "dist", ignore_errors=True)

    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        "--onefile",
        "--windowed",
        "--name",
        exe_name,
        "--additional-hooks-dir",
        str(HOOKS_DIR),
    ]

    if icon_ok:
        cmd.extend(["--icon", str(icon_path)])
    if sys.platform.startswith("win"):
        cmd.extend(["--version-file", str(version_path)])

    cmd.append("modbus_scanner_app.py")

    try:
        _run(cmd)
    except subprocess.CalledProcessError as exc:
        return exc.returncode

    exe_suffix = ".exe" if sys.platform.startswith("win") else ""
    exe_path = ROOT / "dist" / f"{exe_name}{exe_suffix}"

    if not exe_path.exists():
        print(f"Build finished but `{exe_path}` was not found.", file=sys.stderr)
        return 3

    if not args.no_zip:
        zip_path = ROOT / "release" / f"{exe_name}-{version}-portable.zip"
        _zip_portable(exe_path, zip_path)

    print(f"Built: {exe_path}")
    if not args.no_zip:
        print(f"Portable zip: {zip_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
